# Generated by Django 5.1.15 on 2026-10-04 00:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RackLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seal_number', models.CharField(max_length=60)),
                ('locked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rack_locks', to=settings.AUTH_USER_MODEL)),
                ('loft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rack_locks', to='core.loft')),
                ('roll', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rack_lock', to='core.clothroll')),
            ],
            options={
                'ordering': ['-locked_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('seal_number', ''), _negated=True), name='racklock_seal_number_nonempty'), models.UniqueConstraint(condition=models.Q(('voided_at__isnull', True)), fields=('loft', 'seal_number'), name='uniq_active_seal_per_loft')],
            },
        ),
    ]
